name: build-and-push

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: LeavePulse/service-toolkit/.github/workflows/reusable-build-ghcr.yml@71598238ad369add82cff53e0001ac4930f7a194
    secrets: inherit
